### ISSUE TITLE
Add slave to occupation type list?

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_documentation#6]
We have found entries with slave roles in the SI Add files. Should we add "slave" to the occupation type list and if so, how? (since slaves may occupy a range of roles...)

**Comment by ebeshero** [comment]
We have also found police roles.

**Comment by alnopa9** [comment]
@ebeshero I was browsing the TEI guidelines and found the element [`<socecStatus>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-socecStatus.html). With this, you wouldn't need to reconfigure the `<occupation>` tags for slaves.

**Comment by lmwilson** [comment]
@ebeshero We had also discussed adding these: 
for clergy, subtype=rector
for scholar, subtype=professor

**Comment by ebeshero** [comment]
@lmwilson @alnopa9 @NADGIT @frabbitry Here's our thinking after a little research: 
1) It makes sense for us to code law enforcement as `<occupation type="legal" subtype="enforcement">`
2) For the slavery occupation, we looked into the new `<socecStatus>` element and its examples in the TEI Guidelines. 
    * The examples are showing national statistics classification documents (official documents) that hold official socio-economic category codes. The problem for us is that these classification systems emerge in the 20th/ 21st century and they aren't necessarily helpful for our project. So we are not going to adopt this element in the project, but thanks for looking it up! 
    * Once we see Mitford begin to discuss slaves in history in fiction in more specificity (if we do), we will begin working out how to add this category to our occupation types and subtypes. The example of "slave" in the site index file under discussion is about Shakespeare's character, Caliban, who isn't really part of Mitford's corpus of writing. For this character, we can add the denomination of "slave" to the `<note>` element on the entry.
